/*Vivy has a mysterious box which when given two non-negative integral inputs gives out an integral output seemingly at random. The box has also the following text engraved on itself. With some difficulty, Vivy figured out that the box works like a function f such that
f(0,0) = 0
f(0,a) = a
f(a,0) = a
f(a,b) = f(a-1, f(a-1, b-1))
where a and b are positive integers.


To test out this hypothesis, she has hired you,  a master programmer, to code a program in C which takes two inputs and generates the same output the function f would have generated.


Input Format

A single line containing two integers a and b corresponding to the first and second arguments to the function f.


Output Format

Print the output generated by the function f, i.e., print f(a,b)


Example Input

3 4


Example Output

2*/

// solution:

#include <stdio.h>

int foo(int a, int b)
{
    if (a == 0)
    {
        return b;
    }
    if (b == 0)
    {
        return a;
    }
    int x = foo((a - 1), foo(a - 1, b - 1));
    return x;
}

int main()
{
    int a;
    int b;
    scanf("%d %d", &a, &b);
    printf("%d", foo(a, b));
    return 0;
}